/**
 * Data provenance, modelling assumptions and references.
 *
 * A decision tool that cannot say where its numbers came from is not
 * decision support, it is a demo. This file is the register: what is
 * measured, what is assumed, what is synthetic, and what each assumption
 * is worth if it is wrong.
 *
 * It is deliberately blunt about the synthetic rate history. That is the
 * weakest part of the evidence base and the first thing a reviewer
 * should be told, not the last thing they discover.
 */

export const DATA_SOURCES = [
  {
    dataset: 'Freight rate history',
    status: 'synthetic',
    detail:
      '75,600 rows across 140 origin/destination/class series, generated by data/generate_reference_data.py with a mean-reverting level, annual seasonality, and correlated congestion and supply signals.',
    why: 'No public tick-level dry bulk rate series exists for these specific lanes without a commercial licence.',
    consequence:
      'Model accuracy is measured against a process we wrote. It demonstrates the pipeline works; it does not prove forecast skill on the real market. Upload a real series on the Backtest tab to test that.',
  },
  {
    dataset: 'Port restrictions',
    status: 'reference',
    detail:
      'Maximum draft, LOA, beam, berth count and cargo handling rate for 17 ports, 7 East Coast Indian and 10 load ports.',
    why: 'Published port particulars. Values are indicative and rounded.',
    consequence:
      'These drive vessel feasibility directly, so an error changes the recommendation. Verify against the port authority before fixing.',
  },
  {
    dataset: 'Vessel class particulars',
    status: 'reference',
    detail:
      'Deadweight, summer draft, LOA, beam and service speed for Handysize, Supramax, Panamax and Capesize.',
    why: 'Representative values for each class, not a specific ship.',
    consequence:
      'A real fixture uses the actual vessel particulars, which will differ. The ranking logic is unchanged.',
  },
  {
    dataset: 'Sea distances',
    status: 'approximated',
    detail: 'Great-circle distance multiplied by a 1.18 routing factor.',
    why: 'Approximates the deviation a real route takes around land.',
    consequence:
      'Understates any lane that crosses land. Vostochny to Paradip computes 3,171 nm against roughly 5,000 nm via Malacca. Affects voyage days and hire cost on Pacific lanes.',
  },
  {
    dataset: 'USD/INR rate',
    status: 'live',
    detail:
      'European Central Bank daily reference rate via Frankfurter, with open.er-api.com as fallback.',
    why: 'Published daily, keyless, and carries its own date.',
    consequence: 'Rupee figures are only as current as the date shown in the masthead.',
  },
  {
    dataset: 'Vessel positions',
    status: 'live-optional',
    detail: 'Data Docked AIS when a key is configured, otherwise the 24-vessel tracked fleet.',
    why: 'Metered account. The map badge always states which source is in use.',
    consequence: 'Positions are illustrative when the badge reads Simulated fleet.',
  },
]

/**
 * Every constant that materially moves an answer.
 *
 * `sensitivity` states what happens if the value is wrong, because a
 * number without an error bar is an assertion.
 */
export const ASSUMPTIONS = [
  {
    name: 'Lightship draft ratio',
    value: '0.35',
    where: 'ml/decision/vessel_optimizer.py',
    basis:
      'A loaded bulk carrier floats at its summer draft; in ballast it sits at roughly 35% of it. Payload is interpolated linearly between the two.',
    sensitivity:
      'Drives draft-limited payload at shallow ports. At Haldia a Supramax carries 24,538 t on 0.35; raising it to 0.40 cuts that by roughly 8% and can add a voyage.',
  },
  {
    name: 'Under-keel clearance',
    value: '0.5 m',
    where: 'ml/decision/vessel_optimizer.py',
    basis: 'Deducted from declared maximum draft before any payload calculation.',
    sensitivity:
      'Port authorities set this and it varies by berth and tide. Each additional 0.5 m removes several thousand tonnes at a draft-restricted port.',
  },
  {
    name: 'Bunker price',
    value: '$620 / tonne',
    where: 'ml/decision/vessel_optimizer.py',
    basis: 'Indicative VLSFO price. Not live.',
    sensitivity:
      'Enters every class equally, so it shifts absolute cost more than the ranking. A 20% move changes all-in cost per tonne by roughly 3 to 5% on a long lane.',
  },
  {
    name: 'Port charges',
    value: '$0.42 / dwt per call',
    where: 'ml/decision/vessel_optimizer.py',
    basis: 'Proxy that scales with vessel size rather than a tariff lookup.',
    sensitivity:
      'Penalises multi-voyage options, so it matters most at draft-restricted ports where the parcel is split.',
  },
  {
    name: 'Congestion queue scale',
    value: '9 days',
    where: 'ml/decision/idle_management.py',
    basis:
      'Berth waiting grows convexly with utilisation; this scales the expected queue, softened by berth count.',
    sensitivity:
      'Drives requirement (c) idle time and demurrage exposure entirely. The underlying congestion signal is synthetic.',
  },
  {
    name: 'Routing factor',
    value: '1.18',
    where: 'data/generate_reference_data.py',
    basis: 'Mean deviation of a sea route from the great circle across the lanes modelled.',
    sensitivity: 'Understates lanes crossing land. See the sea distance note above.',
  },
  {
    name: 'Systematic shock share',
    value: '0.75',
    where: 'ml/decision/contract_strategy.py',
    basis:
      'Freight markets trend, so successive fixtures are correlated. 75% of the shock is shared across fixtures in a simulation, 25% is idiosyncratic.',
    sensitivity:
      'Set this to 0 and the spot programme diversifies its own risk away, and a term contract never wins. It is the single assumption that decides the Objective.',
  },
  {
    name: 'Risk aversion',
    value: '0.5',
    where: 'ml/decision/contract_strategy.py',
    basis:
      'Weight on the conditional value at risk of the worst 20% of spot outcomes, versus expected cost.',
    sensitivity:
      'At 0 the comparison is pure expected cost and spot always wins. At 1 it is pure tail risk. The spot/term crossover sits near 20% rate volatility at 0.5.',
  },
  {
    name: 'Term premium asymptote',
    value: '9%',
    where: 'ml/decision/contract_strategy.py',
    basis:
      'Owners price duration risk above the expected spot level, widening and flattening with tenor.',
    sensitivity: 'Moves the spot/term crossover directly. Not calibrated against quoted COA terms.',
  },
  {
    name: 'Mean reversion speed',
    value: '0.15 / day',
    where: 'ml/decision/longstaff_schwartz.py',
    basis: 'Rate paths revert toward the quantile forecast rather than drifting freely.',
    sensitivity:
      'Higher values pull paths to the forecast faster and shorten the optimal wait. At 0 the model becomes a random walk and timing loses its signal.',
  },
  {
    name: 'Forecast horizon',
    value: '14 days',
    where: 'ml/preprocessing/preprocess.py',
    basis:
      'Chosen because next-day forecasting is close to unbeatable by persistence and is not the question the problem statement asks.',
    sensitivity:
      'At 1 day the model loses to a naive baseline by 2%. At 14 days it beats it by 10.14% on the synthetic series.',
  },
  {
    name: 'Random seed',
    value: '26006',
    where: 'shared, Python and JavaScript',
    basis: 'The problem statement number, so a demo produces the same answer twice.',
    sensitivity:
      'None on expectations. Monte Carlo probabilities move by well under a percentage point across seeds at these path counts.',
  },
]

export const REFERENCES = [
  {
    cite: 'Longstaff, F. A. and Schwartz, E. S. (2001)',
    title: 'Valuing American Options by Simulation: A Simple Least-Squares Approach',
    where: 'Review of Financial Studies 14(1), 113-147',
    used_for:
      'The optimal-stopping model behind requirement (a). Chartering is the same structure as an American option: exercise now at a known price, or wait and accept the market later.',
  },
  {
    cite: 'International Maritime Organization',
    title: 'International Convention on Load Lines, 1966, as amended',
    where: 'IMO',
    used_for:
      'The load line and summer draft concept the draft-limited payload calculation rests on, and the mark the favicon draws.',
  },
  {
    cite: 'Ke, G. et al. (2017)',
    title: 'LightGBM: A Highly Efficient Gradient Boosting Decision Tree',
    where: 'Advances in Neural Information Processing Systems 30',
    used_for: 'The gradient boosting implementation used for quantile regression.',
  },
  {
    cite: 'Koenker, R. and Bassett, G. (1978)',
    title: 'Regression Quantiles',
    where: 'Econometrica 46(1), 33-50',
    used_for:
      'The pinball loss the Q10/Q50/Q90 models optimise, and the basis for reporting interval coverage rather than only a point error.',
  },
  {
    cite: 'Papadopoulos, H., Gammerman, A. and Vovk, V. (2008)',
    title: 'Normalized Nonconformity Measures for Regression Conformal Prediction',
    where:
      'Proceedings of the IASTED International Conference on Artificial Intelligence and Applications',
    used_for:
      'The prediction interval on the Backtest tab. Scoring the residual against local volatility rather than banding at a fixed width took measured coverage from 66% to 82% against an 80% target on the sample lane.',
  },
  {
    cite: 'Lei, J. et al. (2018)',
    title: 'Distribution-Free Predictive Inference for Regression',
    where: 'Journal of the American Statistical Association 113(523), 1094-1111',
    used_for:
      'Split conformal prediction, including the finite-sample level correction, and the exchangeability assumption a time series only approximately satisfies.',
  },
  {
    cite: 'Rockafellar, R. T. and Uryasev, S. (2000)',
    title: 'Optimization of Conditional Value-at-Risk',
    where: 'Journal of Risk 2(3), 21-41',
    used_for: 'The CVaR measure used to compare a spot programme against a term contract.',
  },
  {
    cite: 'Baltic Exchange',
    title: 'Baltic Dry Index and route assessments',
    where: 'balticexchange.com',
    used_for:
      'The route and vessel class taxonomy the synthetic series imitates. Not used as a data source: assessments are licensed.',
  },
  {
    cite: 'UN/CEFACT',
    title: 'UN/LOCODE, Code for Trade and Transport Locations',
    where: 'UNECE',
    used_for:
      'Port identifiers throughout, for example INPRT for Paradip and AUPHE for Port Hedland.',
  },
]

/**
 * Honest positioning against what already exists.
 *
 * Every one of these does parts of this job, most of them better in
 * their own area. The gap claimed here is narrow on purpose.
 */
export const ALTERNATIVES = [
  {
    name: 'Veson IMOS',
    kind: 'Commercial platform',
    does: 'Full voyage estimation, chartering workflow, P&L, position management. Industry standard for operators.',
    gap: 'Estimates a voyage you specify. It does not rank discharge ports by draft-limited payload for a fixed parcel, and it does not answer market entry timing as an optimal-stopping problem.',
    cost: 'Enterprise licence',
  },
  {
    name: 'Clarksons SIN',
    kind: 'Market intelligence',
    does: 'Authoritative rate assessments, fleet and trade data, the reference source for the market.',
    gap: 'Supplies data, not a decision. It will tell you the rate; it will not tell you whether to fix today.',
    cost: 'Subscription',
  },
  {
    name: 'Baltic Exchange',
    kind: 'Rate benchmark',
    does: 'Publishes route assessments and indices that the market settles against.',
    gap: 'A benchmark, not a tool. No port constraints, no vessel selection, no timing.',
    cost: 'Licensed',
  },
  {
    name: 'Q88 / VesselsValue',
    kind: 'Vessel data',
    does: 'Vessel particulars, questionnaires, valuations.',
    gap: 'Per-vessel reference data. No lane economics and no procurement decision.',
    cost: 'Subscription',
  },
  {
    name: 'Manual chartering desk',
    kind: 'Current practice',
    does: 'Daily market contact, broker relationships, judgement built over years.',
    gap: 'Reactive by construction. The problem statement names this directly: no predictive insight, no systematic view of which port and class is cheapest for a given parcel.',
    cost: 'Staff time',
  },
  {
    name: 'This prototype',
    kind: 'Decision support',
    does: 'Ranks all seven discharge ports by draft-limited all-in cost, answers entry timing by optimal stopping, sizes idle exposure, and compares spot against term on a risk-adjusted basis.',
    gap: 'Runs on a synthetic rate history. It is a decision layer, not a data source, and is designed to sit on top of a licensed feed rather than replace one.',
    cost: 'Open source',
  },
]
